$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: diabetes-deployment
endpoint_name: diabetes-endpoint
model: azureml:prod-active-diabetes:1
instance_type: Standard_D2as_v4
instance_count: 1
